# Generated by Django 2.1.7 on 2019-03-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20190302_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='grade',
            new_name='score',
        ),
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default='Skelbimas be pavadinimo', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='headline',
            field=models.CharField(default='Atsiliepimas', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hello.Post'),
        ),
    ]
