# Generated by Django 2.2.1 on 2019-05-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20190416_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(default='Post without title', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='headline',
            field=models.CharField(default='Review', max_length=200),
        ),
    ]
