# Generated by Django 2.2.1 on 2019-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('kitchen', 'Kitchen'), ('transportation', 'Transportation')], max_length=30),
        ),
    ]
